#This code is based on Syssi's great work! https://github.com/syssi/esphome-jk-bms
#I just cleaned up for the ease of use. //Klatremis

substitutions:
  name: battery-monitor
  device_description: "Monitor Seplos BMS via RS485"
  battery_bank0: "battery bank 0"
  # battery_bank0: "battery bank 1"
  # battery_bank0: "battery bank 2"

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-seplos-bms"
    version: 1.1.0

  on_boot: 
    - priority: 600
      then: 
      - output.turn_on: pin16_high
      - output.turn_on: pin17_high
      - output.turn_on: pin19_high

esp32:
  board: esp32dev

output:
  - platform: gpio
    pin: 16
    id: pin16_high
    
  - platform: gpio
    pin: 17
    id: pin17_high
    
  - platform: gpio
    pin: 19
    id: pin19_high 

external_components:
  - source: github://syssi/esphome-seplos-bms@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

web_server:

logger:
  level: DEBUG

api:

uart:
  id: uart_0
  baud_rate: 19200
  tx_pin: 22
  rx_pin: 21
  rx_buffer_size: 384

seplos_modbus:
  id: modbus0
  uart_id: uart_0

seplos_bms:
  - id: battery_bank0
    # Dip switch configuration of the first pack / address 0x00
    #  8    7    6    5    4    3    2   1
    # off, off, off, off, off, off, off, off
    address: 0x00
    # Known protocol versions: 0x20 (Seplos)
    protocol_version: 0x20
    seplos_modbus_id: modbus0
    update_interval: 15s
  # - id: battery_bank1
  #   # Dip switch configuration of the second pack / address 0x01
  #   #  8    7    6    5    4    3   2    1
  #   # off, off, off, off, off, off, off, on
  #   address: 0x01
  #   # Known protocol versions: 0x20 (Seplos)
  #   protocol_version: 0x20
  #   seplos_modbus_id: modbus0
  #   update_interval: 10s
  # - id: battery_bank2
  #   # Dip switch configuration of the third pack / address 0x02
  #   #  8    7    6    5    4    3   2   1
  #   # off, off, off, off, off, off, on, off
  #   address: 0x02
  #   # Known protocol versions: 0x20 (Seplos)
  #   protocol_version: 0x20
  #   seplos_modbus_id: modbus0
  #   update_interval: 10s

sensor:
  - platform: seplos_bms
    seplos_bms_id: battery_bank0
    min_cell_voltage:
      name: "${battery_bank0} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank0} max cell voltage"
    min_voltage_cell:
      name: "${battery_bank0} min voltage cell"
    max_voltage_cell:
      name: "${battery_bank0} max voltage cell"
    delta_cell_voltage:
      name: "${battery_bank0} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank0} average cell voltage"
    temperature_1:
      name: "${battery_bank0} temperature 1"
    temperature_2:
      name: "${battery_bank0} temperature 2"
    temperature_3:
      name: "${battery_bank0} temperature 3"
    temperature_4:
      name: "${battery_bank0} temperature 4"
    temperature_5:
      name: "${battery_bank0} environment temperature"
    temperature_6:
      name: "${battery_bank0} mosfet temperature"
    total_voltage:
      name: "${battery_bank0} total voltage"
    current:
      name: "${battery_bank0} current"
    power:
      name: "${battery_bank0} power"
    charging_power:
      name: "${battery_bank0} charging power"
    discharging_power:
      name: "${battery_bank0} discharging power"
    residual_capacity:
      name: "${battery_bank0} residual capacity"
    battery_capacity:
      name: "${battery_bank0} battery capacity"
    rated_capacity:
      name: "${battery_bank0} rated capacity"
    state_of_charge:
      name: "${battery_bank0} state of charge"
    charging_cycles:
      name: "${battery_bank0} charging cycles"
    state_of_health:
      name: "${battery_bank0} state of health"
    port_voltage:
      name: "${battery_bank0} port voltage"
    cell_voltage_1:
      name: "${battery_bank0} cell voltage 1"
    cell_voltage_2:
      name: "${battery_bank0} cell voltage 2"
    cell_voltage_3:
      name: "${battery_bank0} cell voltage 3"
    cell_voltage_4:
      name: "${battery_bank0} cell voltage 4"
    cell_voltage_5:
      name: "${battery_bank0} cell voltage 5"
    cell_voltage_6:
      name: "${battery_bank0} cell voltage 6"
    cell_voltage_7:
      name: "${battery_bank0} cell voltage 7"
    cell_voltage_8:
      name: "${battery_bank0} cell voltage 8"
    cell_voltage_9:
      name: "${battery_bank0} cell voltage 9"
    cell_voltage_10:
      name: "${battery_bank0} cell voltage 10"
    cell_voltage_11:
      name: "${battery_bank0} cell voltage 11"
    cell_voltage_12:
      name: "${battery_bank0} cell voltage 12"
    cell_voltage_13:
      name: "${battery_bank0} cell voltage 13"
    cell_voltage_14:
      name: "${battery_bank0} cell voltage 14"
    cell_voltage_15:
      name: "${battery_bank0} cell voltage 15"
    cell_voltage_16:
      name: "${battery_bank0} cell voltage 16"

  # - platform: seplos_bms
  #   seplos_bms_id: battery_bank1
  #   min_cell_voltage:
  #     name: "${battery_bank1} min cell voltage"
  #   max_cell_voltage:
  #     name: "${battery_bank1} max cell voltage"
  #   min_voltage_cell:
  #     name: "${battery_bank1} min voltage cell"
  #   max_voltage_cell:
  #     name: "${battery_bank1} max voltage cell"
  #   delta_cell_voltage:
  #     name: "${battery_bank1} delta cell voltage"
  #   average_cell_voltage:
  #     name: "${battery_bank1} average cell voltage"
  #   temperature_1:
  #     name: "${battery_bank1} temperature 1"
  #   temperature_2:
  #     name: "${battery_bank1} temperature 2"
  #   temperature_3:
  #     name: "${battery_bank1} temperature 3"
  #   temperature_4:
  #     name: "${battery_bank1} temperature 4"
  #   temperature_5:
  #     name: "${battery_bank1} environment temperature"
  #   temperature_6:
  #     name: "${battery_bank1} mosfet temperature"
  #   total_voltage:
  #     name: "${battery_bank1} total voltage"
  #   current:
  #     name: "${battery_bank1} current"
  #   power:
  #     name: "${battery_bank1} power"
  #   charging_power:
  #     name: "${battery_bank1} charging power"
  #   discharging_power:
  #     name: "${battery_bank1} discharging power"
  #   residual_capacity:
  #     name: "${battery_bank1} residual capacity"
  #   battery_capacity:
  #     name: "${battery_bank1} battery capacity"
  #   rated_capacity:
  #     name: "${battery_bank1} rated capacity"
  #   state_of_charge:
  #     name: "${battery_bank1} state of charge"
  #   charging_cycles:
  #     name: "${battery_bank1} charging cycles"
  #   state_of_health:
  #     name: "${battery_bank1} state of health"
  #   port_voltage:
  #     name: "${battery_bank1} port voltage"
  #   cell_voltage_1:  
  #     name: "${battery_bank1} cell voltage 1"
  #   cell_voltage_2:
  #     name: "${battery_bank1} cell voltage 2"
  #   cell_voltage_3:
  #     name: "${battery_bank1} cell voltage 3"
  #   cell_voltage_4:
  #     name: "${battery_bank1} cell voltage 4"
  #   cell_voltage_5:
  #     name: "${battery_bank1} cell voltage 5"
  #   cell_voltage_6:
  #     name: "${battery_bank1} cell voltage 6"
  #   cell_voltage_7:
  #     name: "${battery_bank1} cell voltage 7"
  #   cell_voltage_8:
  #     name: "${battery_bank1} cell voltage 8"
  #   cell_voltage_9:
  #     name: "${battery_bank1} cell voltage 9"
  #   cell_voltage_10:
  #     name: "${battery_bank1} cell voltage 10"
  #   cell_voltage_11:
  #     name: "${battery_bank1} cell voltage 11"
  #   cell_voltage_12:
  #     name: "${battery_bank1} cell voltage 12"
  #   cell_voltage_13:
  #     name: "${battery_bank1} cell voltage 13"
  #   cell_voltage_14:
  #     name: "${battery_bank1} cell voltage 14"
  #   cell_voltage_15:
  #     name: "${battery_bank1} cell voltage 15"
  #   cell_voltage_16:
  #     name: "${battery_bank1} cell voltage 16"


  # - platform: seplos_bms
  #   seplos_bms_id: battery_bank2
  #   min_cell_voltage:
  #     name: "${battery_bank2} min cell voltage"
  #   max_cell_voltage:
  #     name: "${battery_bank2} max cell voltage"
  #   min_voltage_cell:
  #     name: "${battery_bank2} min voltage cell"
  #   max_voltage_cell:
  #     name: "${battery_bank2} max voltage cell"
  #   delta_cell_voltage:
  #     name: "${battery_bank2} delta cell voltage"
  #   average_cell_voltage:
  #     name: "${battery_bank2} average cell voltage"
  #   temperature_1:
  #     name: "${battery_bank2} temperature 1"
  #   temperature_2:
  #     name: "${battery_bank2} temperature 2"
  #   temperature_3:
  #     name: "${battery_bank2} temperature 3"
  #   temperature_4:
  #     name: "${battery_bank2} temperature 4"
  #   temperature_5:
  #     name: "${battery_bank2} environment temperature"
  #   temperature_6:
  #     name: "${battery_bank2} mosfet temperature"
  #   total_voltage:
  #     name: "${battery_bank2} total voltage"
  #   current:
  #     name: "${battery_bank2} current"
  #   power:
  #     name: "${battery_bank2} power"
  #   charging_power:
  #     name: "${battery_bank2} charging power"
  #   discharging_power:
  #     name: "${battery_bank2} discharging power"
  #   residual_capacity:
  #     name: "${battery_bank2} residual capacity"
  #   battery_capacity:
  #     name: "${battery_bank2} battery capacity"
  #   rated_capacity:
  #     name: "${battery_bank2} rated capacity"
  #   state_of_charge:
  #     name: "${battery_bank2} state of charge"
  #   charging_cycles:
  #     name: "${battery_bank2} charging cycles"
  #   state_of_health:
  #     name: "${battery_bank2} state of health"
  #   port_voltage:
  #     name: "${battery_bank2} port voltage"
  #   cell_voltage_1:  
  #     name: "${battery_bank2} cell voltage 1"
  #   cell_voltage_2:
  #     name: "${battery_bank2} cell voltage 2"
  #   cell_voltage_3:
  #     name: "${battery_bank2} cell voltage 3"
  #   cell_voltage_4:
  #     name: "${battery_bank2} cell voltage 4"
  #   cell_voltage_5:
  #     name: "${battery_bank2} cell voltage 5"
  #   cell_voltage_6:
  #     name: "${battery_bank2} cell voltage 6"
  #   cell_voltage_7:
  #     name: "${battery_bank2} cell voltage 7"
  #   cell_voltage_8:
  #     name: "${battery_bank2} cell voltage 8"
  #   cell_voltage_9:
  #     name: "${battery_bank2} cell voltage 9"
  #   cell_voltage_10:
  #     name: "${battery_bank2} cell voltage 10"
  #   cell_voltage_11:
  #     name: "${battery_bank2} cell voltage 11"
  #   cell_voltage_12:
  #     name: "${battery_bank2} cell voltage 12"
  #   cell_voltage_13:
  #     name: "${battery_bank2} cell voltage 13"
  #   cell_voltage_14:
  #     name: "${battery_bank2} cell voltage 14"
  #   cell_voltage_15:
  #     name: "${battery_bank2} cell voltage 15"
  #   cell_voltage_16:
  #     name: "${battery_bank2} cell voltage 16"
